### PR TITLE
working on SanctSound processing

### PR DESCRIPTION
**Pull request by MathewBiddle**
I will leave this as a draft until we work through the issues in #147

### CODE REVIEW

**Comment by MathewBiddle** [comment]
I believe the SanctSound data should be ready to go. I've adjusted the lat/lon pairs that were problematic and reran all my tests. Let me know when you're available to review.

**Comment by albenson-usgs** [comment]
This is looking good. I don't know how I missed this before but `eventID` is missing from the occurrence file so there is no way to link the event measurements, which is all the measurements in the emof, to the corresponding event. You also don't need to repeat these in the emof for each occurrence. For example eventID "CI01_1_2018-11-01" there are three measurements (moored instrument depth, acoustic frequency, sound pressure level) but there are nine rows in the emof for this event because those measurements are being repeated for the bocaccio and humpback whale and plainfin midshipman occurrences. 
Capture
So there should only be three rows in the emof and the occurrenceID should be blank for all three rows because none of these are measurements of the occurrence. Hopefully this makes sense. Happy to meet to walk through it.

I was also thinking we should add `samplingProtocol` = "passive acoustic monitoring" unless Carrie has a sampling protocol we can reference. That way people at least know what kind of sampling this is if they are pulling all records for humpback whales for instance. This is not required so no need to do it if it's a pain. I was going to skip it but since the emof needs required fixes I figured it would be worth adding this as well.

**Comment by MathewBiddle** [comment]
Thanks for the quick check. I think I was saving the wrong dataframe. Let me take a look. 

> So there should only be three rows in the emof and the occurrenceID should be blank for all three rows because none of these are measurements of the occurrence. Hopefully this makes sense. Happy to meet to walk through it.

I was iterating through `occurrenceID` not `eventID`. I'll need to adjust my script to account for this.

**Comment by albenson-usgs** [comment]
> My hypothesis is that I wrote out each emof (eg. moored instrument depth) for each occurrence. I think that is still valid given the emof values will change based on species.

Ok that wasn't clear to me and is now so that makes sense (and is valid that there will occasionally be repeats). So these need to be linked to the occurrences and not the events. We still need to add eventID to the emof file because this will be an event core dataset (meaning eventID is the key between the tables). But no need to make any other changes.

**Comment by MathewBiddle** [comment]
Sounds good.

Just to be clear, we will keep the `occurrenceID` in both occurrence and emof tables?

**Comment by albenson-usgs** [comment]
Yes!

**Comment by albenson-usgs** [comment]
Yes that would be great to add depth into the occurrence file using minDIM and maxDIM! Thanks for making the connections to the sampling methods 🙌

**Comment by MathewBiddle** [comment]
Updated:

emof - https://github.com/MathewBiddle/bio_data_guide/blob/sanctsound/datasets/SanctSound/data/emof.zip
occurrence - https://github.com/MathewBiddle/bio_data_guide/blob/sanctsound/datasets/SanctSound/data/occurrence_w_coordinateUncertainty.zip

Hopefully these address the above comments.

**Comment by MathewBiddle** [comment]
Yeah, Carrie would be the one for the metadata. We could point her to https://ioos.github.io/mbon-docs/metadata-eml.html

**Review by albenson-usgs — APPROVED** [review]
Changes look good to me!

**Comment by MathewBiddle** [comment]
closes #147

**Pull request merged**
