### PR TITLE
adding edna example as submodule

### PR DESCRIPTION
**Pull request by MathewBiddle**
adding the iobis edna example as a submodule in datasets/. 

Addresses part of #89

### CODE REVIEW

**Comment by MathewBiddle** [comment]
This might break some stuff, but let's merge and see what happens 🤷

**Comment by MathewBiddle** [comment]
I had a feeling it wouldn't work:
https://github.com/ioos/bio_data_guide/runs/6815033444?check_suite_focus=true#step:6:268

Need to figure out how to have GH Actions [git clone with submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). Something like:
```
git clone --recurse-submodules https://github.com/chaconinc/MainProject
```

**Comment by 7yl4r** [comment]
For submodules I usually do the clone, cd in, then run the following:

```
# initialize (if needed) & update all submodules
git submodule update --init --recursive --remote
```

**Comment by MathewBiddle** [comment]
ahh, I figured out that the GH Action checkout had a submodule option:
https://github.com/ioos/bio_data_guide/blob/7762ab129411b4fd9ed6c10452ec5b1d2298200a/.github/workflows/deploy_bookdown.yml#L16-L18

**Comment by MathewBiddle** [comment]
closes #73

**Pull request merged**
