### PR TITLE
add presentations folder and NOAA Omics seminar slides from 2024-04-17

### PR DESCRIPTION
**Pull request by sformel-usgs**

### CODE REVIEW

**Comment by sformel-usgs** [comment]
@MathewBiddle not 100% sure this is where you wanted these slides from today.  If it is, could you please merge the PR?

**Comment by MathewBiddle** [comment]
FYI, if we stick it on the `gh-pages` branch, the html will be rendered into a webpage. See my tests here https://mathewbiddle.github.io/bio_data_guide/noaa_omics_seminar_2024-04-17.html#/title-slide

**Comment by sformel-usgs** [comment]
Yes, I have the source files, but it ends up being pretty large, so I made it a self-contained html.  My preference is to just serve the slides as a webpage, like you've suggested.  Though, when I go to the link you shared, it says 'page not found.'

**Comment by MathewBiddle** [comment]
Future thought - have a presentations folder for other, related presentations. Bonus - figure out how to add that as another webpage to the compendium.

**Pull request merged**
