### PR TITLE
making Abby's notebook first in Applications chapter

### PR DESCRIPTION
**Pull request by MathewBiddle**
Abby's notebook should be first as it's more general than the others.

### CODE REVIEW

**Comment by albenson-usgs** [comment]
I updated the notebook in January. Any idea why that's not also updating here? https://github.com/ioos/bio_data_guide/blob/main/datasets/TPWD_HARC_BagSeine/TPWD_HARC_BagSeine_OBISENV.md

**Comment by MathewBiddle** [comment]
interesting... for reference: https://github.com/ioos/bio_data_guide/blob/main/datasets/TPWD_HARC_BagSeine/TPWD_HARC_BagSeine_OBISENV.md

**Comment by 7yl4r** [comment]
For clarification: the confusion here is resolved, right? From what I can see the .md matches up with the text and is listed first in the applications chapter.

**Comment by MathewBiddle** [comment]
yup, See #97

**Pull request merged**
